workflows:
  android-workflow:
    name: Mahadev APK
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Create android folder
        script: |
          if [ ! -f "android/app/build.gradle" ]; then
            flutter create . --platforms=android --project-name mahadev_player --org com.mahadev
          fi
      - name: FORCE Add Internet Permission
        script: |
          FILE="android/app/src/main/AndroidManifest.xml"
          echo "--- BEFORE ---"
          cat $FILE
          # On ajoute la permission si elle n'existe pas
          if ! grep -q "INTERNET" $FILE; then
            sed -i '/<manifest/a \    <uses-permission android:name="android.permission.INTERNET" />' $FILE
            sed -i '/<manifest/a \    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />' $FILE
          fi
          echo "--- AFTER ---"
          cat $FILE
      - name: Get packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk