workflows:
  android-workflow:
    name: Mahadev APK
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - script: flutter pub get
      - script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk